// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActiveInfo: typeof import('./../components/ActiveInfo.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    OverView: typeof import('./../components/OverView.vue')['default']
    PlateQuantityCom: typeof import('./../components/PlateQuantityCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTrend: typeof import('./../components/SearchTrend.vue')['default']
    SideBar: typeof import('./../components/SideBar.vue')['default']
    SiteSituation: typeof import('./../components/SiteSituation.vue')['default']
    VisualData: typeof import('./../components/VisualData.vue')['default']
  }
}
