// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NavBar: typeof import('./../components/NavBar.vue')['default']
    OverView: typeof import('./../components/OverView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../components/SideBar.vue')['default']
    SiteSituation: typeof import('./../components/SiteSituation.vue')['default']
  }
}
