// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActiveInfo: typeof import('./../components/ActiveInfo.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    ModuleAdd: typeof import('./../components/ModuleAdd.vue')['default']
    ModuleControl: typeof import('./../components/ModuleControl.vue')['default']
    ModuleEdit: typeof import('./../components/ModuleEdit.vue')['default']
    ModuleList: typeof import('./../components/ModuleList.vue')['default']
    ModuleManagement: typeof import('./../components/ModuleManagement.vue')['default']
    ModuleSwitch: typeof import('./../components/ModuleSwitch.vue')['default']
    ModuleSwitchItem: typeof import('./../components/ModuleSwitchItem.vue')['default']
    ModuleSwitchShadow: typeof import('./../components/ModuleSwitchShadow.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    OverView: typeof import('./../components/OverView.vue')['default']
    PlateQuantityCom: typeof import('./../components/PlateQuantityCom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTrend: typeof import('./../components/SearchTrend.vue')['default']
    SideBar: typeof import('./../components/SideBar.vue')['default']
    SiteSituation: typeof import('./../components/SiteSituation.vue')['default']
    TopicList: typeof import('./../components/TopicList.vue')['default']
    TopicManagement: typeof import('./../components/TopicManagement.vue')['default']
    TopicSearch: typeof import('./../components/TopicSearch.vue')['default']
    TopicTurePage: typeof import('./../components/TopicTurePage.vue')['default']
    VisualData: typeof import('./../components/VisualData.vue')['default']
  }
}
